import { builtinModules } from 'node:module';
import tailwindcss from '@tailwindcss/vite';
import { createLogger, defineConfig, type Plugin } from 'vite';

const banner = `/*! THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN — see the plugin repository for source. */`;

// node-pty's module-level code eagerly loads the native binary at import time:
// lib/index.js requires lib/unixTerminal.js, which calls `loadNativeModule('pty')`
// and reads `native.dir + '/spawn-helper'`. Obsidian's plugin loader evaluates
// main.js with `__dirname` pointing at Electron's renderer init dir, not the
// plugin folder, so the native path has to come from the plugin at runtime.
//
// These transforms defer the whole node-pty chain until the first `spawn`/open
// call. By then, main.ts's ShellPlugin has run setNativePtyDir() and the
// patched loadNativeModule knows where to look. The dev fallback resolves the
// rebuilt binary under node_modules/node-pty/build/Release.
function patchNodePty(): Plugin {
  return {
    name: 'obsidian-shell:patch-node-pty',
    transform(code, id) {
      const normalized = id.replace(/\\/g, '/');
      if (normalized.endsWith('/node-pty/lib/utils.js')) {
        const pattern = /function loadNativeModule\([\s\S]*?\n\}/;
        if (!pattern.test(code)) {
          this.error('Failed to locate loadNativeModule in node-pty/lib/utils.js');
        }
        const replacement = `var __obsidianShellNativeDir = null;
function __obsidianShellSetNativeDir(dir) { __obsidianShellNativeDir = dir; }
exports.__obsidianShellSetNativeDir = __obsidianShellSetNativeDir;
function loadNativeModule(name) {
    var path = require('path');
    var platform = process.platform + '-' + process.arch;
    var dir = __obsidianShellNativeDir;
    if (!dir) {
        throw new Error('obsidian-shell: native dir not initialized before loading ' + name + '.node');
    }
    var candidates = [
        path.join(dir, name + '-' + platform + '.node'),
        path.join(dir, 'node_modules', 'node-pty', 'build', 'Release', name + '.node'),
    ];
    var lastError;
    for (var i = 0; i < candidates.length; i++) {
        try {
            return { dir: path.dirname(candidates[i]), module: require(candidates[i]) };
        } catch (e) {
            lastError = e;
        }
    }
    throw new Error('Failed to load native module ' + name + '.node, checked: ' + candidates.join(', ') + ': ' + lastError);
}`;
        return { code: code.replace(pattern, replacement), map: null };
      }

      if (normalized.endsWith('/node-pty/lib/unixTerminal.js')) {
        // Release assets land as flat files, so the plugin folder holds every
        // platform's `spawn-helper` side by side. Pick the one matching the
        // runtime platform. Fall back to the unsuffixed name for local dev
        // where pnpm rebuild:native emits a single `spawn-helper`.
        const helperPattern = /var helperPath = native\.dir \+ '\/spawn-helper';/;
        if (!helperPattern.test(code)) {
          this.error('Failed to locate spawn-helper resolution in node-pty/lib/unixTerminal.js');
        }
        const helperReplacement = `var helperPath = (function () {
    var fs = require('fs');
    var suffixed = native.dir + '/spawn-helper-' + process.platform + '-' + process.arch;
    return fs.existsSync(suffixed) ? suffixed : native.dir + '/spawn-helper';
})();`;
        return { code: code.replace(helperPattern, helperReplacement), map: null };
      }

      if (normalized.endsWith('/node-pty/lib/index.js')) {
        // Defer platform-specific terminal ctor lookup and exports.native so
        // nothing in node-pty tries to load the binary at bundle import time.
        const ctorPattern =
          /var terminalCtor;\s*if \(process\.platform === 'win32'\) \{\s*terminalCtor = require\('\.\/windowsTerminal'\)\.WindowsTerminal;\s*\}\s*else \{\s*terminalCtor = require\('\.\/unixTerminal'\)\.UnixTerminal;\s*\}/;
        const nativePattern =
          /exports\.native = \(process\.platform !== 'win32' \? utils_1\.loadNativeModule\('pty'\)\.module : null\);/;
        if (!ctorPattern.test(code) || !nativePattern.test(code)) {
          this.error('Failed to locate patchable statements in node-pty/lib/index.js');
        }
        let patched = code.replace(
          ctorPattern,
          `var __terminalCtor;
function __getTerminalCtor() {
    if (!__terminalCtor) {
        __terminalCtor = process.platform === 'win32'
            ? require('./windowsTerminal').WindowsTerminal
            : require('./unixTerminal').UnixTerminal;
    }
    return __terminalCtor;
}
var terminalCtor = new Proxy(function () {}, {
    construct: function (_, args) { return Reflect.construct(__getTerminalCtor(), args); },
    get: function (_, prop) { return __getTerminalCtor()[prop]; },
});`,
        );
        patched = patched.replace(
          nativePattern,
          `Object.defineProperty(exports, 'native', {
    configurable: true,
    get: function () { return process.platform !== 'win32' ? utils_1.loadNativeModule('pty').module : null; },
});`,
        );
        return { code: patched, map: null };
      }

      return null;
    },
  };
}

// Silence Vite's "outDir is the same directory as root" warning. The build
// intentionally emits main.js into the plugin folder (which Obsidian loads
// directly) and guards against clobbering sources with `emptyOutDir: false`.
const logger = createLogger();
const origWarn = logger.warn.bind(logger);
logger.warn = (msg, opts) => {
  if (typeof msg === 'string' && msg.includes('build.outDir must not be the same directory')) {
    return;
  }
  origWarn(msg, opts);
};

export default defineConfig(({ mode }) => {
  const isProd = mode === 'production';

  return {
    customLogger: logger,
    plugins: [tailwindcss(), patchNodePty()],
    build: {
      lib: {
        entry: 'src/main.ts',
        formats: ['cjs'],
        fileName: () => 'main.js',
        cssFileName: 'styles',
      },
      rollupOptions: {
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          /^@lezer\//,
          ...builtinModules,
          ...builtinModules.map((m) => `node:${m}`),
        ],
        output: {
          exports: 'default',
          banner,
        },
      },
      target: 'es2022',
      // External source maps (`main.js.map`, `styles.css.map`) so the build
      // ships them alongside the built assets on GitHub releases without
      // bloating the main bundle with inline maps.
      sourcemap: true,
      minify: isProd,
      emptyOutDir: false,
      outDir: '.',
      copyPublicDir: false,
    },
  };
});
