import { builtinModules } from 'node:module';
import tailwindcss from '@tailwindcss/vite';
import { createLogger, defineConfig, type Plugin } from 'vite';

const banner = `/*! THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN — see the plugin repository for source. */`;

// Rewrite node-pty's loadNativeModule so it resolves flat <name>-<platform>-<arch>.node
// files next to main.js first (the released plugin layout), then falls back to the
// upstream node_modules/node-pty/build/Release layout for local development, where
// `pnpm rebuild:native` writes the binary.
function patchNodePtyBindings(): Plugin {
  return {
    name: 'obsidian-shell:patch-node-pty-bindings',
    transform(code, id) {
      const normalized = id.replace(/\\/g, '/');
      if (!normalized.endsWith('/node-pty/lib/utils.js')) {
        return null;
      }
      const pattern = /function loadNativeModule\([\s\S]*?\n\}/;
      if (!pattern.test(code)) {
        this.error('Failed to locate loadNativeModule in node-pty/lib/utils.js');
      }
      const replacement = `function loadNativeModule(name) {
    var path = require('path');
    var platform = process.platform + '-' + process.arch;
    var candidates = [
        path.join(__dirname, name + '-' + platform + '.node'),
        path.join(__dirname, 'node_modules', 'node-pty', 'build', 'Release', name + '.node'),
    ];
    var lastError;
    for (var i = 0; i < candidates.length; i++) {
        try {
            return { dir: path.dirname(candidates[i]), module: require(candidates[i]) };
        } catch (e) {
            lastError = e;
        }
    }
    throw new Error('Failed to load native module ' + name + '.node, checked: ' + candidates.join(', ') + ': ' + lastError);
}`;
      return { code: code.replace(pattern, replacement), map: null };
    },
  };
}

// Silence Vite's "outDir is the same directory as root" warning. We intentionally
// emit main.js into the plugin folder (which Obsidian loads directly) and guard
// against clobbering sources with `emptyOutDir: false`.
const logger = createLogger();
const origWarn = logger.warn.bind(logger);
logger.warn = (msg, opts) => {
  if (typeof msg === 'string' && msg.includes('build.outDir must not be the same directory')) {
    return;
  }
  origWarn(msg, opts);
};

export default defineConfig(({ mode }) => {
  const isProd = mode === 'production';

  return {
    customLogger: logger,
    plugins: [tailwindcss(), patchNodePtyBindings()],
    build: {
      lib: {
        entry: 'src/main.ts',
        formats: ['cjs'],
        fileName: () => 'main.js',
        cssFileName: 'styles',
      },
      rollupOptions: {
        external: [
          'obsidian',
          'electron',
          '@codemirror/autocomplete',
          '@codemirror/collab',
          '@codemirror/commands',
          '@codemirror/language',
          '@codemirror/lint',
          '@codemirror/search',
          '@codemirror/state',
          '@codemirror/view',
          /^@lezer\//,
          ...builtinModules,
          ...builtinModules.map((m) => `node:${m}`),
        ],
        output: {
          exports: 'default',
          banner,
        },
      },
      target: 'es2022',
      // External source maps (`main.js.map`, `styles.css.map`) so we can
      // ship them alongside the built assets on GitHub releases without
      // bloating the main bundle with inline maps.
      sourcemap: true,
      minify: isProd,
      emptyOutDir: false,
      outDir: '.',
      copyPublicDir: false,
    },
  };
});
